CFLAGS = -g -O2 -Wall -Werror -I $(NEJUDGE_DIR)/include
NEJUDGE_DIR ?= ../../../nejudge

ifneq ($(wildcard solution.c),)
SOLUTION_SRC ?= solution.c
else ifneq ($(wildcard simpleio_x86_64.S),)
SOLUTION_SRC ?= solution.S simpleio_x86_64.S
else
SOLUTION_SRC ?= solution.S
endif

solution: $(SOLUTION_SRC)
	$(CC) $(CFLAGS) $(SOLUTION_SRC) -o $@

clean:
	-rm solution

test: solution
	@set -a; [ -f config.env ] && . ./config.env; set +a; python3 $(NEJUDGE_DIR)/test.py --user ejexec

docker-test:
	docker run --rm -it -v "$(realpath ../../../)":/caos -w /caos/"$$(realpath --relative-to=$(realpath ../../../) .)" caos make test
