CFLAGS ?= -g -O2
CFLAGS += -Wall -Werror -I $(NEJUDGE_DIR)/include
COMPILER ?= $(CC)

PROJECT_DIR := $(realpath $(dir $(abspath $(lastword $(MAKEFILE_LIST))))/..)
TASK_REL_DIR := $(patsubst $(PROJECT_DIR)/%,%,$(CURDIR))
DOCKER_IMAGE_NAME=caos


ifeq ($(strip $(SOLUTION_SRC)),)

ifneq ($(wildcard solution.c),)
SOLUTION_SRC := solution.c
else ifneq ($(wildcard simpleio_x86_64.S),)
SOLUTION_SRC := solution.S simpleio_x86_64.S
else ifneq ($(wildcard solution.S),)
SOLUTION_SRC := solution.S
else ifneq ($(wildcard solution.h),)
SOLUTION_DEPS += solution.h
else
$(error No default solution source found)
endif

ifneq ($(wildcard main.c),)
SOLUTION_SRC += main.c
else ifneq ($(wildcard main.S),)
SOLUTION_SRC += main.S
else ifneq ($(wildcard main.cpp),)
SOLUTION_SRC += main.cpp
COMPILER = $(CXX)
endif

endif


ifneq ($(wildcard wrappers.cfg),)
SOLUTION_SRC += wrappers.c
WRAPPERS_CFG := @wrappers.cfg
endif


ifneq ($(wildcard interactor.c),)
NEJUDGE_FLAGS += --interactor ./interactor
SOLUTION_DEPS += interactor
endif


ifneq ($(wildcard interactor.py),)
NEJUDGE_FLAGS += --interactor ./interactor.py
SOLUTION_DEPS += interactor.py
endif


all: test

static:

solution: $(SOLUTION_SRC) $(SOLUTION_DEPS)
	$(COMPILER) $(CFLAGS) $(SOLUTION_SRC) $(WRAPPERS_CFG) -o $@ $(LDFLAGS)

interactor: interactor.c
	$(CC) -O2 -g interactor.c -o$@

clean:
	@rm -rf solution interactor run static


_pretest:

_test: solution static _pretest
	@set -a; [ -f config.env ] && . ./config.env; set +a; python3 "$(PROJECT_DIR)/nejudge/test.py" --user ejexec $(NEJUDGE_FLAGS)

_posttest: _test

test: _posttest

_prepare-answers:
	make test NEJUDGE_FLAGS="$(NEJUDGE_FLAGS) --prepare-answers"


UNAME_M := $(shell uname -m)
DOCKER_BUILD_PLATFORM :=
ifeq ($(UNAME_M),arm64)
DOCKER_BUILD_PLATFORM := --platform linux/amd64
endif

docker-build:
	docker build $(DOCKER_BUILD_PLATFORM) $(dir $(abspath $(lastword $(MAKEFILE_LIST)))) -t $(DOCKER_IMAGE_NAME)

_check-docker-image:
	@docker image inspect $(DOCKER_IMAGE_NAME) >/dev/null 2>&1 || { \
		echo "Ошибка: docker image '"$(DOCKER_IMAGE_NAME)"' не найден. Сначала запустите 'make docker-build'."; \
		exit 1; \
	}

docker: _check-docker-image
	docker run --rm -it -e GITLAB_CI=true -e NEJUDGE_FORCE_CHECK_STYLE=1 -v "$(PROJECT_DIR):/caos" -w "/caos/$(TASK_REL_DIR)" $(DOCKER_IMAGE_NAME) make $(filter-out $@,$(MAKECMDGOALS))


.PHONY: all clean test docker docker-build _check-docker-image _fill-answers pretest posttest
